apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: argocd
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: https
    port: 443
    targetPort: 8080
  selector:
    app: argocd-server
  type: LoadBalancer
---
# Inne manifesty Argo CD, takie jak Deployments, ConfigMaps, Secrets, itp.
