name: Reuse TF scaning workflow

on:
  push:
    branches:
       - main
    # Uncommento to stop triggers on changes of the workflow
    # comment to trigger on "TF testing" script development
    # paths:
    #   - 'TF/**'
    
permissions:
  contents: read   
  
jobs:
  call_tf_testing:
    uses: xaprun/terraform-ci-cd/.github/workflows/tf-scan-bundle.yml@main
    with:
      branch: main

